### ISSUE TITLE
Delete all namespaces when creating a new namespace in ns-create.sh 

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-mcks#109]
아래의 코드와 같이 namespace를 생성할 때 기존 모든 namespace를 지우도록 된 것으로 보입니다.
의도된 것인지 또는 단순 버그인지 검토 부탁드립니다.

https://github.com/cloud-barista/cb-mcks/blob/deaed83d524dec05e953f0520b5069a5206df8bd/docs/test/ns-create.sh#L36

**Comment by vlatte** [comment]
수정하여 반영하였습니다. (#112)
