### ISSUE TITLE
What action is needed when failing to delete a cluster

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-mcks#110]
o 테스트 버전: cb-mcks v0.4.3
o 상황: 
우연히 아래와 같이 클러스터 삭제가 실패하는 경우가 발생했습니다. 다시 삭제를 요청해도 동일한 에러가 발생합니다.
클러스터 삭제 실패의 경우 대응 방안이 필요해 보입니다.
참고로 최신 버전에서 발생 여부는 확인해보지 못했습니다.

```
INFO[1151] duration := 8m1.415511172s
INFO[1440] start delete Cluster (name=mcas-cluster)
INFO[1441] terminate MCIS (name=mcas-cluster)INFO[1446] delete MCIS (name=mcas-cluster)
WARN[1447] Tumblebug : statusCode=500, url=http://localhost:1323/tumblebug/ns/lb-ns/mcis/mcas-cluster, body={"message":"MCIS mcas-cluster is Running-3(3/3) and not Terminated/Undefined/Failed, Deletion is not allowed (use option=force for force deletion)"}
INFO[1447] refine mcis (name=mcas-cluster)
INFO[1448] delete MCIS (name=mcas-cluster)
WARN[1449] Tumblebug : statusCode=500, url=http://localhost:1323/tumblebug/ns/lb-ns/mcis/mcas-cluster, body={"message":"MCIS mcas-cluster is Running-3(3/3) and not Terminated/Undefined/Failed, Deletion is not allowed (use option=force for force deletion)"}
ERRO[1449] delete MCIS error : MCIS mcas-cluster is Running-3(3/3) and not Terminated/Undefined/Failed, Deletion is not allowed (use option=force for force deletion)
ERRO[1449] MCIS mcas-cluster is Running-3(3/3) and not Terminated/Undefined/Failed, Deletion is not allowed (use option=force for force deletion)
```

**Comment by seokho-son** [comment]
CB-TB에서는 MCIS Terminate 가 선행되어야 Delete가 가능합니다.
예전에 MCKS에 관련 사항을 알려드렸으므로~ 아마 잘 처리가 되어 있으리라 생각합니다.
아마도 FW간 버전의 차이 때문이 아닐까 싶네요.. ^^

**Comment by sykim-etri** [comment]
@seokho-son MCIS terminate가 선행되었지만 delete가 실패한 경우로 보입니다. 말씀하신 것처럼 CB-TB를 최신 버전으로 올려서 테스트하여 발생한 에러일 수도 있겠습니다. 다만 알 수 없는 이유로 delete가 실패한 경우에라도 MCKS에서 먼가 대응을 해줘야 하지 않을까 하는 의견입니다.
참고로 CB-TB에 force 옵션으로 해당 mcis 삭제를 요청하면 삭제할 수 있긴 했습니다.

**Comment by sykim-etri** [comment]
상기 이슈는 최신 CB-TB(commit add82bb0)에서 terminate 관련 방식이 변경되어서 발생한 현상으로 추정됩니다. CB-TB의 소스코드 기반 개발 환경을 구축하는 동안 최신 버전으로 테스트가 진행되는 바람에 생긴 현상인 것 같습니다.
아마도 MCKS에 해당 내용이 반영되면 거의 발생하지 않을 이슈일 것 같습니다.
추후 신규 terminate 방식을 반영하여 동작 시 문제가 없으면 이슈를 닫아도 될 것으로 판단됩니다.

**Comment by vlatte** [comment]
@sykim-etri 말씀하신대로 Tumblebug에서 terminate, refine 관련된 부분이 변경되었고, MCKS에서도 반영하였습니다. (#98) (commit [25c8d05](https://github.com/cloud-barista/cb-mcks/commit/25c8d05507811727bfb4c85ee391662c38ce720c))
MCKS 최신 버전을 사용하시면 발생하지 않을 것으로 보입니다.

참고로 현재까지 테스트한 버전은 CB-Spider v0.4.13, CB-Tumblebug v0.4.11 입니다.

**Comment by sykim-etri** [comment]
@vlatte 감사합니다~
