### ISSUE TITLE
HTTP GET Method RFC2731 Compliance Request

### ISSUE THREAD

**Issue by joowons** [cloud-barista/cb-mcks#125]
- https://github.com/cloud-barista/cb-spider/issues/557 
  
  http get 요청 시 body 보내는 부분이 있다면 Query Parameter로 변경 요청.
  예) ConnectionName := c.QueryParam("connectionName")

**Comment by powerkimhub** [comment]
@joowons 

- 혹시, 관련 API가 존재한다면 변경 보다는 추가 고려해주시면 좋을 듯합니다. 
  - 사유: Backward Compatibility

**Comment by jihoon-seo** [comment]
이 이슈를 close한 PR #126 은 CB-MCKS가 CB-Tumblebug을 호출할 때 GET 호출의 불필요한 body 내용물을 없애는 PR로 보입니다.

한편, 이 이슈는 'CB-MCKS의 REST API 중에서 GET 이면서도 body를 받고 있는 것이 있다면
body를 안 받도록 변경하거나
QueryParam 으로 받는 방법도 추가하자' 라는 취지의 이슈로 보입니다.

따라서, 혹시 'CB-MCKS의 REST API 중에서 GET 이면서도 body를 받고 있는 것이 있다면'
이 이슈는 다시 오픈해야 할 것으로 보이는데요,
@itnpeople 어떻게 생각하시나요? 😊

**Comment by joowons** [comment]
@jihoon-seo 
제가 설명을 좀 부족하게 쓴것 같습니다. 확인한 결과 CB-MCKS의 REST API 에서 그런 경우는 없었고
찾아보니 CB-Tumblebug을 호출할 때 GET 사용시 불필요한 body 부분이 있어서 그 부분 반영한 PR입니다.
