### ISSUE TITLE
 Implement API that provides VM specs that can be deployed and operated by CSP

### ISSUE THREAD

**Issue by joowons** [cloud-barista/cb-mcks#127]
CSP별 배포 및 운영이 가능한 VM 사양 제공 기능

**URL spec**

* [GET] /mcks/mcir/connections/:connectionname/specs
* output
```
{
  "kind": "SpecList"
  "items": [
    {
      "name": "string",
      "cpu": {
        clock: "string",
        count: "string"
     },
     "memory": "string",
     "gpu": {
       "mfr": "string",
       "count": "string",
       "memory": "string",
       "modedl": "string"
      }
    }
  ]
}
```  
- 제한 rule 및 조회 조건 검토
  - min  :  2 cpu / 2 GB memory

**Comment by itnpeople** [comment]
**Installing kubeadm**
* https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#before-you-begin
* 2 GB or more of RAM per machine (any less will leave little room for your apps).
* 2 CPUs or more.
