### ISSUE TITLE
When deleting a cluster, cb-ladybug does not delete some MCIRs(vpc, sshkey, firewall, ...)

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-mcks#38]
클러스터를 하나 생성한 후 해당 클러스터를 삭제하고 나면 더 이상 사용되지 않는 VPC와 ssh key 등이 그대로 남아있는 현상이 있었습니다. 그러다 보니 다시 클러스터를 생성할 때 동일한 ssh key가 존재하면서 생성에 실패한 바 있습니다.(aws-northeast-2)

클러스터 생성시 VPC나 ssh key 등이 없는 경우 새로 생성하고 있는데 CB-Ladybug가 생성했던 자원이라면 클러스터 삭제시 이를 확인하여 불필요한 자원인 경우 삭제하는 것이 바람직할 것으로 보입니다.

간단히 생각했을때 꼬이는 부분이 있을 것으로 예상됩니다만 검토를 부탁드립니다.

**Comment by itnpeople** [comment]
다른 vm 에서 사용하는 vpc, ssh-key  일수도  있을텐데요

**Comment by sykim-etri** [comment]
1. 다른 VM에서 사용 여부는 파악이 불가능한가요?
2. 파악이 불가능하다면 Vpc나 sshkey도 자체 생성하지 않고 사용자로부터 입력을 받도록 수정하는 것이 바람직할 수도 있어보입니다.

**Comment by itnpeople** [comment]
그럼 지난번 회의 협의 되었던 api- spec 은 어떻게돼야 할까요

**Comment by sykim-etri** [comment]
@itnpeople Vpc나 sshkey를 사용자로부터 입력 받는 것에 대한 의견은 어떠신가요?

**Comment by itnpeople** [comment]
어떤 의견을 말씀하시는건지는 잘 모르겠는데 지금 수정은 할 순 없고요
꼭 필요하다면 6월 이후 일정 잡아서 진행 해야지 않을까요
그런데 ladybug 에서만 논의 해서 결정 할 사항은 아니지 않나요..

**Comment by sykim-etri** [comment]
@itnpeople
1. 말씀하신 것 처럼 당장 수정해야 할 시급한 이슈는 아닙니다.
2. 멀티 CSP 지원을 위한 API 확장을 하는 상황이라서, 방향이 결정된다면 API 수준에서는 함께 진행하는 것이 낫지 않을까 생각됩니다. API만 열어두고 입력되는 vpc, sshkey 등은 무시하고 현재 코드를 그대로 사용할 수 있어 보입니다.
3. 먼저 Ladybug 내에서 논의하고 다음 정기 회의에서 논의하면 될 것으로 생각됩니다. 그런데 타 프레임워크와 관련된 부분이 있나요? 저는 특별히 타 프레임워크와는 연관된 부분은 없는 것으로 보여서요.
4. 의견을 여쭤본 부분은 현행 방안을 개선하는 방안(사용하지 않는 경우를 파악해서 삭제)과 사용자로부터 입력 받아서 처리하는 방안에 대해서 어떤 의견을 가지고 계신지 해서요.
