### ISSUE TITLE
Improve conn-config-registering procedure

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-mcks#74]
**What would you like to be enhanced**
: 
https://github.com/cloud-barista/cb-ladybug/tree/master/docs/test#cloud-connection-info-%EB%93%B1%EB%A1%9D
에 소개되어 있는
conn config 등록 절차가
사용자 입장에서는 약간 번거로운 측면이 있습니다.

[TB 사례]
- [`conf.env`](https://github.com/cloud-barista/cb-tumblebug/blob/main/src/testclient/scripts/conf.env): 모든 CSP의 region 정보를 기록해 놓았습니다.
AWS를 예로 들면, 총 21개의 리전을 기록해 놓았습니다.
사용자가 테스트 스크립트를 사용할 때, `./create-vNet.sh aws 2 jhseo` 라고 명령을 내리면
`conf.env` 에서 AWS 부분의 2번째 위치에 있는 `Canada (Central)` 리전을 사용하는 것입니다.
- [`credentials.conf.example`](https://github.com/cloud-barista/cb-tumblebug/blob/main/src/testclient/scripts/credentials.conf.example): 사용자가 이 파일을 복사하여 `credentials.conf` 파일을 만들고
여기에 credential 관련 정보를 적어 놓으면
사용자가 `./register-cloud.sh` (Spider 에 conn config 등록하는 script) 실행할 때
`credentials.conf` 파일의 내용을 읽어서 Spider에 등록합니다.
- ...

**Why is this needed**
: 

**Proposed solution**
:
예를 들어, https://github.com/cloud-barista/cb-ladybug/tree/master/docs/test#cloud-connection-info-%EB%93%B1%EB%A1%9D 에서
`REGION`, `ZONE` 등의 환경변수를 계속 재활용하여 사용하고 있어서
- GCP 등록할 때, AWS 등록할 때, Azure 등록할 때 매번 업데이트 해 주어야 합니다.
- 실행 순서에 유의해야 합니다.

이를
GCP 관련 env var 에는 `GCP_` 라는 prefix 를 붙이는 식으로 CSP 별로 구분하고
파일로 만든 다음 (예: `cloud-connection-info.env`)
사용자가 이 파일을 업데이트하도록 하고
`./connectioninfo-create.sh` 파일 실행 시 `cloud-connection-info.env` 에 있는 환경변수를 읽도록 하는
방안이 있을 수 있습니다.

**Comment by sykim-etri** [comment]
REGION, ZONE 등의 환경 변수는 구분하는 것이 바람직해 보입니다.
전반적인 개선 방안은 추후 고민해보겠습니다. 감사합니다.
